version: '2'
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    container_name: zoo1
    
    environment:
        - ZOO_SERVER_ID=1
        - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
     - "2181"

  kafka:
  
    image: 'bitnami/kafka:latest'
    
    environment:
      - KAFKA_CFG_NODE_ID=0      
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  
      
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
      
