version: '3.8'
services:
zoo1:
    image: bitnami/zookeeper:latest
    restart: always
    hostname: zoo1
    networks:
        - zkkc
    environment:
        - ZOO_SERVER_ID=1
        - ALLOW_ANONYMOUS_LOGIN=yes

kaf1:
    depends_on:
        - zoo1
    networks:
        - zkkc
    image: bitnami/kafka:latest
    hostname: kaf1
    environment:
        - KAFKA_BROKER_ID=1
        - ALLOW_PLAINTEXT_LISTENER=true
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kaf1:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
    ports:
        - "9092"
