version: '3.8'
services:
mongodb:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONOG_INITDB_ROOT_USERNAME: ${MONOG_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6
zoo1:
    image: bitnami/zookeeper:latest
    restart: always
    hostname: zoo1
    networks:
        - zkkc
    environment:
        - ZOO_SERVER_ID=1
        - ALLOW_ANONYMOUS_LOGIN=yes

kaf1:
    depends_on:
        - zoo1
    networks:
        - zkkc
    image: bitnami/kafka:latest
    hostname: kaf1
    environment:
      KAFKA_BROKER_ID=1
      KAFKA_PROCESS_ROLES
      KAFKA_INTER_BROKER_LISTENER_NAME:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES:CONTROLLER
      KAFKA_PROCESS_ROLES:controller,broker
      KAFKA_CONTROLLER_QUORUM_NAMES:"1@localhost:9093"
      ALLOW_PLAINTEXT_LISTENER=true
      KAFKA_LISTENERS:PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS:/var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1      
      KAFKA_AUTO_CREATE_TOPICS_ENABLE:"true"
      KAFKA_LOG_RETENTION_HOURS:2
      KAFKA_MIN_INSYNC_REPLICAS:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      KAFKA_LOG_RETENTION_BYTES:1073741824
      KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
      - "9093:9093"
